// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntagbernphgvnvoqgkxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50YWdiZXJucGhndm52b3Fna3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjc5NzUsImV4cCI6MjA2OTgwMzk3NX0.MlFyQ4NajGtgtzEMZVRWyXgyKglnpJAFYbgRnKwJ_n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});